name: Run main_papermc_crawler.py and create papermc direct download links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # every day at four (six)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x64"
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: execute py script
        run: python main_papermc_crawler.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated papermc download links" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 