name: Run main_vanilla_crawler.py and create release_vanilla_downloads.json and snapshot_vanilla_downloads.json

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 */3 * *' # every day at four (six)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: execute py script
        run: python main_vanilla_crawler.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated vanilla download links" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 